cd %~dp0
copy "..\ChatManager.cs" "C:\Users\power\AppData\Roaming\SpaceEngineers\Mods\Text To Speech mod\Data\Scripts\folder required here"
copy "..\OutputManager.cs" "C:\Users\power\AppData\Roaming\SpaceEngineers\Mods\Text To Speech mod\Data\Scripts\folder required here"
copy "..\AttendanceManager.cs" "C:\Users\power\AppData\Roaming\SpaceEngineers\Mods\Text To Speech mod\Data\Scripts\folder required here"
copy "..\SpeechBlock.cs" "C:\Users\power\AppData\Roaming\SpaceEngineers\Mods\Text To Speech mod\Data\Scripts\folder required here"
copy "..\SentenceFactory.cs" "C:\Users\power\AppData\Roaming\SpaceEngineers\Mods\Text To Speech mod\Data\Scripts\folder required here"
copy "..\MarekVoice.cs" "C:\Users\power\AppData\Roaming\SpaceEngineers\Mods\Text To Speech mod\Data\Scripts\folder required here"
copy "..\HawkingVoice.cs" "C:\Users\power\AppData\Roaming\SpaceEngineers\Mods\Text To Speech mod\Data\Scripts\folder required here"
copy "..\GLADOSVoice.cs" "C:\Users\power\AppData\Roaming\SpaceEngineers\Mods\Text To Speech mod\Data\Scripts\folder required here"
copy "..\VoiceTemplate.cs" "C:\Users\power\AppData\Roaming\SpaceEngineers\Mods\Text To Speech mod\Data\Scripts\folder required here"
copy "..\Pronunciation.cs" "C:\Users\power\AppData\Roaming\SpaceEngineers\Mods\Text To Speech mod\Data\Scripts\folder required here"
copy "..\WordIsolator.cs" "C:\Users\power\AppData\Roaming\SpaceEngineers\Mods\Text To Speech mod\Data\Scripts\folder required here"
copy "..\PrettyScaryDictionary.cs" "C:\Users\power\AppData\Roaming\SpaceEngineers\Mods\Text To Speech mod\Data\Scripts\folder required here"
copy "..\SoundPlayer.cs" "C:\Users\power\AppData\Roaming\SpaceEngineers\Mods\Text To Speech mod\Data\Scripts\folder required here"
pause